// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFIL6EjbCJgUTrOFIA5IfoX-R8Hg6C4LA',
    appId: '1:783611658147:web:d3956a5f3b74b9a0a1a416',
    messagingSenderId: '783611658147',
    projectId: 'emp-desh',
    authDomain: 'emp-desh.firebaseapp.com',
    storageBucket: 'emp-desh.firebasestorage.app',
    measurementId: 'G-18GWL2RHCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVSWROezGrrwuNWRyzyDWVG2AC-jZITzg',
    appId: '1:783611658147:android:28e915abb230116ca1a416',
    messagingSenderId: '783611658147',
    projectId: 'emp-desh',
    storageBucket: 'emp-desh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUU2Gg_CkAL7zIE_ABdvkIjfVanoWIAb0',
    appId: '1:783611658147:ios:0a5d218ed9a80e59a1a416',
    messagingSenderId: '783611658147',
    projectId: 'emp-desh',
    storageBucket: 'emp-desh.firebasestorage.app',
    iosBundleId: 'com.example.employeeTrackingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUU2Gg_CkAL7zIE_ABdvkIjfVanoWIAb0',
    appId: '1:783611658147:ios:0a5d218ed9a80e59a1a416',
    messagingSenderId: '783611658147',
    projectId: 'emp-desh',
    storageBucket: 'emp-desh.firebasestorage.app',
    iosBundleId: 'com.example.employeeTrackingSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFIL6EjbCJgUTrOFIA5IfoX-R8Hg6C4LA',
    appId: '1:783611658147:web:75eae9c133ef3d82a1a416',
    messagingSenderId: '783611658147',
    projectId: 'emp-desh',
    authDomain: 'emp-desh.firebaseapp.com',
    storageBucket: 'emp-desh.firebasestorage.app',
    measurementId: 'G-L8YBL1SPKJ',
  );

}